# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kvstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekvstream.proto\x12\x10refract.kvstream\"J\n\tColumnDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\nvalue_type\x18\x02 \x01(\x0e\x32\x1b.refract.kvstream.ValueType\"]\n\rRegisterTable\x12\x10\n\x08table_id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x07\x63olumns\x18\x03 \x03(\x0b\x32\x1b.refract.kvstream.ColumnDef\",\n\x08TableRow\x12\x10\n\x08table_id\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x01(\x0c\"\x86\x01\n\rStreamMessage\x12\x39\n\x0eregister_table\x18\x01 \x01(\x0b\x32\x1f.refract.kvstream.RegisterTableH\x00\x12/\n\ttable_row\x18\x02 \x01(\x0b\x32\x1a.refract.kvstream.TableRowH\x00\x42\t\n\x07payload\"+\n\x0eStreamResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t*\x7f\n\tValueType\x12\x0b\n\x07\x46LOAT32\x10\x00\x12\x0b\n\x07\x46LOAT64\x10\x01\x12\x08\n\x04INT8\x10\x02\x12\t\n\x05INT16\x10\x03\x12\t\n\x05INT32\x10\x04\x12\t\n\x05INT64\x10\x05\x12\t\n\x05UINT8\x10\x06\x12\n\n\x06UINT16\x10\x07\x12\n\n\x06UINT32\x10\x08\x12\n\n\x06UINT64\x10\t2Y\n\x08KVStream\x12M\n\x06Stream\x12\x1f.refract.kvstream.StreamMessage\x1a .refract.kvstream.StreamResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUETYPE']._serialized_start=435
  _globals['_VALUETYPE']._serialized_end=562
  _globals['_COLUMNDEF']._serialized_start=36
  _globals['_COLUMNDEF']._serialized_end=110
  _globals['_REGISTERTABLE']._serialized_start=112
  _globals['_REGISTERTABLE']._serialized_end=205
  _globals['_TABLEROW']._serialized_start=207
  _globals['_TABLEROW']._serialized_end=251
  _globals['_STREAMMESSAGE']._serialized_start=254
  _globals['_STREAMMESSAGE']._serialized_end=388
  _globals['_STREAMRESPONSE']._serialized_start=390
  _globals['_STREAMRESPONSE']._serialized_end=433
  _globals['_KVSTREAM']._serialized_start=564
  _globals['_KVSTREAM']._serialized_end=653
# @@protoc_insertion_point(module_scope)
